version: '3.3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./config/supervisord.conf:/etc/supervisord.conf
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
